version: "3"
services:
  db:
    #どのイメージを使うか？
    image: mysql:8.0
    #認証形式に関する設定
    command: --default-authentication-plugin=mysql_native_password
    #同期設定 ローカル側の/src/db/mysql_dataのファイルをコンテナ側の/var/lib/mysqlファイルと同期させるという意味
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    # 環境変数の設定 MYSQL_ROOT_PASSWORDという環境変数にpasswordを入れている
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    #この書き方でベースのイメージとして同じディレクトリにあるDockerfileを参照するという意味になる
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
